//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCSCalc.Parameters.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCSCalc.Parameters.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 100.
        /// </summary>
        internal static string AnArbitraryNumberOfPorts_NumberOfPortsDiapason_Max {
            get {
                return ResourceManager.GetString("AnArbitraryNumberOfPorts.NumberOfPortsDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string AnArbitraryNumberOfPorts_NumberOfPortsDiapason_Min {
            get {
                return ResourceManager.GetString("AnArbitraryNumberOfPorts.NumberOfPortsDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1000.
        /// </summary>
        internal static string NonStrictСomplianceWithTheStandart_MaxPermanentLinkDiapason_Max {
            get {
                return ResourceManager.GetString("NonStrictСomplianceWithTheStandart.MaxPermanentLinkDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.01.
        /// </summary>
        internal static string NonStrictСomplianceWithTheStandart_MaxPermanentLinkDiapason_Min {
            get {
                return ResourceManager.GetString("NonStrictСomplianceWithTheStandart.MaxPermanentLinkDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1000.
        /// </summary>
        internal static string NonStrictСomplianceWithTheStandart_MinPermanentLinkDiapason_Max {
            get {
                return ResourceManager.GetString("NonStrictСomplianceWithTheStandart.MinPermanentLinkDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.01.
        /// </summary>
        internal static string NonStrictСomplianceWithTheStandart_MinPermanentLinkDiapason_Min {
            get {
                return ResourceManager.GetString("NonStrictСomplianceWithTheStandart.MinPermanentLinkDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string NonTechnologicalReserve_TechnologicalReserve {
            get {
                return ResourceManager.GetString("NonTechnologicalReserve.TechnologicalReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 100.
        /// </summary>
        internal static string NotAnArbitraryNumberOfPorts_NumberOfPortsDiapason_Max {
            get {
                return ResourceManager.GetString("NotAnArbitraryNumberOfPorts.NumberOfPortsDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        internal static string NotAnArbitraryNumberOfPorts_NumberOfPortsDiapason_Min {
            get {
                return ResourceManager.GetString("NotAnArbitraryNumberOfPorts.NumberOfPortsDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10000.
        /// </summary>
        internal static string StandartValues_CableHankMeterageDiapason_Max {
            get {
                return ResourceManager.GetString("StandartValues.CableHankMeterageDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.01.
        /// </summary>
        internal static string StandartValues_CableHankMeterageDiapason_Min {
            get {
                return ResourceManager.GetString("StandartValues.CableHankMeterageDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10000.
        /// </summary>
        internal static string StandartValues_NumberOfWorkplacesDiapason_Max {
            get {
                return ResourceManager.GetString("StandartValues.NumberOfWorkplacesDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string StandartValues_NumberOfWorkplacesDiapason_Min {
            get {
                return ResourceManager.GetString("StandartValues.NumberOfWorkplacesDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        internal static string StandartValues_TechnologicalReserveDiapason_Max {
            get {
                return ResourceManager.GetString("StandartValues.TechnologicalReserveDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string StandartValues_TechnologicalReserveDiapason_Min {
            get {
                return ResourceManager.GetString("StandartValues.TechnologicalReserveDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 90.
        /// </summary>
        internal static string StrictСomplianceWithTheStandart_MaxPermanentLinkDiapason_Max {
            get {
                return ResourceManager.GetString("StrictСomplianceWithTheStandart.MaxPermanentLinkDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string StrictСomplianceWithTheStandart_MaxPermanentLinkDiapason_Min {
            get {
                return ResourceManager.GetString("StrictСomplianceWithTheStandart.MaxPermanentLinkDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 90.
        /// </summary>
        internal static string StrictСomplianceWithTheStandart_MinPermanentLinkDiapason_Max {
            get {
                return ResourceManager.GetString("StrictСomplianceWithTheStandart.MinPermanentLinkDiapason.Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string StrictСomplianceWithTheStandart_MinPermanentLinkDiapason_Min {
            get {
                return ResourceManager.GetString("StrictСomplianceWithTheStandart.MinPermanentLinkDiapason.Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.10.
        /// </summary>
        internal static string TechnologicalReserveAvailability_TechnologicalReserve_Default {
            get {
                return ResourceManager.GetString("TechnologicalReserveAvailability.TechnologicalReserve.Default", resourceCulture);
            }
        }
    }
}
